package main.java.chess.models.enums;

public enum GameOver {

	CHECKMATE, STALEMATE, DRAW,

	RESIGNATION, AGREED_DRAW,

	TIME_FORFEIT,

	INSUFFICIENT_MATERIAL,

	THREEFOLD_REPETITION, FIVEFOLD_REPETITION, //
	FIFTY_MOVE_RULE, SEVENTY_FIVE_MOVE_RULE;
}
